### ISSUE TITLE
Remove Disnix in sitemap

### ISSUE THREAD

**Issue by Mic92** [nixos-users/wiki#5]
Although it is included in the official nixos homepage, there is not much real-world usage of disnix.
I fear it never left its prototype status and I have not  heard so far of anybody using it except in the few blog post of its creator.

**Comment by Mic92** [comment]
has been done be resolved

**Comment by ixxie** [comment]
@Mic92 - your argument is reasonable and I can see your point, but allow me to offer two counter arguments:

1. Parallelism with the official site is a virtue, since it helps users navigate easier. I know I contradict myself since in another thread I argue for separating the Nix Language from the Nix Package Manager, but I believe in that case we are adding rather than removing, so it helps more than it hurts.

2. It could be a chicken and egg problem: maybe Disnix isn't used much because it lacks documentation, so perhaps we are hurting its cause by omitting it.

So how about this: for now we leave it out as you suggest, but if we build up solid articles for it, and/or get requests for it, we can eventually revisit the issue.

**Comment by Mic92** [comment]
Ok. So far we have zero content for Disnix.
